groups:
    - developer
recipes:
    mac_os_x:
        - sudoalt::default
        - osxdefaults::dock_automatically_hide_and_show_the_dock
        - osxdefaults::dock_do_not_animate_opening_applications_from_the_dock
        - osxdefaults::dock_enable_spring_loading_for_all_dock_items
        - osxdefaults::dock_make_dock_icons_of_hidden_applications_translucent
        - osxdefaults::dock_minimize_to_application
        - osxdefaults::dock_set_the_icon_size_of_dock_items_to_36_pixels
        - osxdefaults::dock_show_indicator_lights_for_open_applications_in_the_dock
        - osxdefaults::dock_enable_highlight_hover_effect_for_the_grid_view_of_a_stack
        - osxdefaults::dock_remove_the_auto-hiding_dock_delay
        - osxdefaults::dock_increase_autohide_speed
        - osxdefaults::menu_add_battery_percentage
        - osxdefaults::menu_show_clock_with_date
        - osxdefaults::set_computer_name
        - osxdefaults::reduce_transparency
        - osxdefaults::dock_set_magnification_on
        - osxdefaults::disable_auto-correct
        - osxdefaults::dark-mode
attributes:
    homebrewalt:
        cask_apps:
            - virtualhostx
            - virtualbox
            - intel-xdk
            - liteicon
            - sketch
            - spotify
            - hermes
            - beyond-compare
            - dropbox
            - bettertouchtool
    git:
        name: Casey Corcoran
        email: casey.corcoran@lightspeedvt.com
    osxdefaults:
        computername: Snap-To-Pixel
        dock:
            tilesize: 48
    authorization:
        sudo:
            users:
                - snaptopixel
            passwordless: true
            include_sudoers_d: true
